param([switch]$Check)
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$catalog = Join-Path $root 'localization'
$languages = Get-Content (Join-Path $catalog 'languages.json') -Raw -Encoding utf8 | ConvertFrom-Json
$english = Get-Content (Join-Path $catalog 'en.json') -Raw -Encoding utf8 | ConvertFrom-Json -AsHashtable
function Save-Or-Check([string]$path, [string]$content) {
    if ($Check) {
        if (!(Test-Path $path) -or ([IO.File]::ReadAllText($path).Replace("`r`n", "`n") -ne $content)) { throw "Generated file is out of date: $path" }
    } else {
        New-Item -ItemType Directory -Force -Path (Split-Path $path -Parent) | Out-Null
        [IO.File]::WriteAllText($path, $content, [Text.UTF8Encoding]::new($false))
    }
}
foreach ($language in $languages) {
    $file = Join-Path $catalog "$($language.tag).json"
    $strings = Get-Content $file -Raw -Encoding utf8 | ConvertFrom-Json -AsHashtable
    if ($language.tag -ne 'en' -and $strings['welcome_body'] -eq $english['welcome_body']) { throw "Untranslated locale: $file" }
    $difference = Compare-Object @($english.Keys | Sort-Object) @($strings.Keys | Sort-Object)
    if ($difference) { throw "Missing or extra translation keys in $file : $($difference | Out-String)" }
    $lines = [Collections.Generic.List[string]]::new()
    $lines.Add('<?xml version="1.0" encoding="utf-8"?>')
    $lines.Add('<!-- Generated by scripts/Generate-Locales.ps1. Edit localization/*.json. -->')
    $lines.Add('<resources>')
    if ($language.tag -eq 'en') {
        $lines.Add('    <string name="app_name" translatable="false">Game Optimizer PRO</string>')
        $lines.Add('    <string name="brand_title" translatable="false">GAME OPTIMIZER</string>')
        $lines.Add('    <string name="pro_badge" translatable="false">PRO</string>')
        $lines.Add('    <string name="network_wifi" translatable="false">Wi-Fi</string>')
        $lines.Add('    <string name="network_ethernet" translatable="false">Ethernet</string>')
        $lines.Add('    <string name="support_url" translatable="false">github.com/seandyadryan/game-optimizer-pro/issues</string>')
        $lines.Add('    <string name="unit_gib" translatable="false">%1$s GiB</string>')
        $lines.Add('    <string name="unit_celsius" translatable="false">%1$s°C</string>')
        $lines.Add('    <string name="ram_fraction" translatable="false">%1$s / %2$s</string>')
        $lines.Add('    <string name="unavailable" translatable="false">—</string>')
    }
    foreach ($key in ($english.Keys | Sort-Object -Culture en-US)) {
        $value = [string]$strings[$key]
        if ([string]::IsNullOrWhiteSpace($value)) { throw "Empty translation: $file $key" }
        $expected = ([regex]::Matches($english[$key], '%\d+\$[sd]') | ForEach-Object Value | Sort-Object) -join ','
        $actual = ([regex]::Matches($value, '%\d+\$[sd]') | ForEach-Object Value | Sort-Object) -join ','
        if ($expected -ne $actual) { throw "Format arguments differ: $file $key" }
        $escaped = [Security.SecurityElement]::Escape($value.Replace('\', '\\').Replace("'", "\'").Replace('"', '\"').Replace("`n", '\n'))
        $lines.Add("    <string name=`"$key`">$escaped</string>")
    }
    $lines.Add('</resources>')
    $folder = if ($language.qualifier) { "values-$($language.qualifier)" } else { 'values' }
    Save-Or-Check (Join-Path $root "app/src/main/res/$folder/strings.xml") (($lines -join "`n") + "`n")
}
$config = @('<?xml version="1.0" encoding="utf-8"?>', '<locale-config xmlns:android="http://schemas.android.com/apk/res/android">')
$config += $languages | ForEach-Object { "    <locale android:name=`"$($_.tag)`" />" }
$config += '</locale-config>'
Save-Or-Check (Join-Path $root 'app/src/main/res/xml/locales_config.xml') (($config -join "`n") + "`n")
$kotlin = @('package com.deploydulupulangnanti/gameoptimizerpro'.Replace('/', '.'), '', '// Generated from localization/languages.json. Names are native autonyms.', 'data class SupportedLanguage(val tag: String, val nativeName: String)', 'val supportedLanguages = listOf(')
$kotlin += $languages | ForEach-Object { "    SupportedLanguage(`"$($_.tag)`", `"$($_.name)`")," }
$kotlin += ')'
Save-Or-Check (Join-Path $root 'app/src/main/java/com/deploydulupulangnanti/gameoptimizerpro/SupportedLanguages.kt') (($kotlin -join "`n") + "`n")
Write-Output "Verified $($languages.Count) languages with $($english.Count) translated strings each."
